_target_: src.models.ae_module.AELitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.legacy.dense_autoencoder.DenseAutoencoder
  input_shape: [1, 28, 28]
  hidden_dims: [512, 256]
  latent_dim: 32

compile: false
