_target_: src.models.score_based_module.ScoreBasedLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0002
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.5
  patience: 10

net:
  _target_: src.models.components.dense_score_model.DenseScoreModel
  input_shape: [1, 28, 28]
  hidden_dims: [512, 512, 256]
  noise_embedding_dim: 64
  sigma_min: 0.01
  sigma_max: 1.0
  num_noise_levels: 100
  sampling_steps_per_level: 10
  sampling_step_size: 0.00001

compile: false
