_target_: src.models.modules.reconstruction.VAELitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

method:
  _target_: src.models.methods.generative.latent_variable.vae.VariationalAutoencoder
  beta: 1.0
  network:
    _target_: src.models.networks.dense.autoencoder.DenseGaussianAutoencoder
    input_shape: [1, 28, 28]
    hidden_dims: [512, 256]
    latent_dim: 32
compile: false
