_target_: src.models.vae_module.VAELitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.dense_vae.DenseVAE
  input_shape: [1, 28, 28]
  hidden_dims: [512, 256]
  latent_dim: 32

beta: 1.0
compile: false
